static char *item_names[] = {
	"Airtight Flask",
	"Scrag of Beast",
	"Beast-Steak",
	"Ambrosial Meat",
	"Sour Scrag of Beast",
	"Sour Beast-Steak",
	"Sour Ambrosial Meat",
	"Rotten Scrag of Beast",
	"Rotten Beast-Steak",
	"Rotten Ambrosial Meat",
	"Small Fish",
	"Large Fish",
	"Giant Fish",
	"Small Rank Fish",
	"Large Rank Fish",
	"Giant Rank Fish",
	"Small Rotten Fish",
	"Large Rotten Fish",
	"Giant Rotten Fish",
	"Berry",
	"Apple",
	"Grandgrapes",
	"Moldy Berry",
	"Moldy Apple",
	"Moldy Grandgrapes",
	"Rotten Berry",
	"Rotten Apple",
	"Rotten Grandgrapes",
	"Twigbean",
	"Carrot",
	"Pumpkin",
	"Moldy Twigbean",
	"Moldy Carrot",
	"Moldy Pumpkin",
	"Rotten Twigbean",
	"Rotten Carrot",
	"Rotten Pumpkin",
	"Egg",
	"Golden Egg",
	"Rotten Egg",
	"Sunbright",
	"Moonglow",
	"Wilted Blossom",
	"Greenwarish",
	"Potent Greenwarish",
	"Mushroom",
	"Large Mushroom",
	"Avernal Mushroom",
	"Mithridate",
	"Bringbout",
	"Small Nut",
	"Large Nut",
	"Copper Ore",
	"Silver Ore",
	"Gold Ore",
	"Fuligin Ore",
	"Hemp",
	"Wool-Cloth",
	"Silk",
	"Argence",
	"Pine Branch",
	"Cedar Branch",
	"Chestnut Branch",
	"Beech Branch",
	"Lantern",
	"Lantern (Half-Full)",
	"Ferrystone",
	"Empty Flask",
	"Flask of Water",
	"Flask of Oil",
	"Kindling",
	"Unknown Item",
	"Ceramic Jug",
	"Rock",
	"Skull",
	"Pickaxe",
	"Lantern (No Fuel)",
	"Unknown Item",
	"Unknown Item",
	"Throwblast",
	"Dragon's Spit",
	"Unknown Item",
	"Smother Sap",
	"Harspud Milk",
	"Harspud Juice",
	"Harspud Sauce",
	"Interventive",
	"Spicy Mushroom Tea",
	"Light-Cure",
	"Unknown Item",
	"Panacea",
	"White Wine",
	"Red Wine",
	"Poison Flask",
	"Absorbent Rag",
	"Clean Cloth",
	"Unknown Item",
	"Secret Softener",
	"Liquid Vim",
	"Salubrious Brew",
	"Bottled Haste",
	"Eyedropper",
	"Throat Drops",
	"Unknown Item",
	"Placative Brew",
	"Liberating Brew",
	"Purifying Brew",
	"Unknown Item",
	"Dose of Strength",
	"Dose of Courage",
	"Warlock's Draught",
	"Cleric's Draught",
	"Conqueror's Periapt",
	"Angel's Periapt",
	"Demon's Periapt",
	"Mage's Periapt",
	"Monk's Periapt",
	"Veteran's Periapt",
	"Banker's Periapt",
	"Isometricine",
	"Foreign Knife",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Wooden Arrow",
	"Poison Arrow",
	"Blinder Arrow",
	"Silencer Arrow",
	"Sleeper Arrow",
	"Oil Arrow",
	"z",
	"Petrifying Arrow",
	"Unknown Item",
	"Blast Arrow",
	"Maker's Finger",
	"Unknown Item",
	"First Key To Salvation",
	"Second Key To Salvation",
	"First Gem of Salvation",
	"Second Gem of Salvation",
	"Third Gem of Salvation",
	"Fourth Gem of Salvation",
	"Watergod's Altar Key",
	"Quarry Key",
	"Portcrystal",
	"Wakestone",
	"Wyrm Hunt License",
	"Gardener's Permit",
	"Ancient Slate",
	"Wakestone Shard",
	"Unknown Item",
	"Unknown Item",
	"Incriminating Contract",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Salomet's Grimoire",
	"Confidential Letter",
	"Parcel",
	"Unknown Item",
	"Altar Slate",
	"Maul's Badge Of Amity",
	"Ophis's Badge Of Amity",
	"Unknown Item",
	"Gold Idol",
	"Blessed Flower",
	"Dead Flower",
	"Ancient Tablet",
	"Fifth Gem of Salvation",
	"Godsbane",
	"Windbluff Tower Key",
	"Arisen's Bond",
	"Unknown Item",
	"Watergod's Altar Lever",
	"Shadow Fort Lever",
	"Wyrmward Perfume",
	"Unknown Item",
	"Unknown Item",
	"Seeker's Token",
	"Badge of Vows",
	"Unknown Item",
	"Engraved Lever",
	"Unknown Item",
	"Unknown Item",
	"First Journal Entry",
	"Second Journal Entry",
	"Third Journal Entry",
	"Fourth Journal Entry",
	"Fifth Journal Entry",
	"Final Journal Entry",
	"Unsigned Letter",
	"Tightly Folded Letter",
	"Silver Idol",
	"Bronze Idol",
	"Unknown Item",
	"Unknown Item",
	"Godsbane",
	"Coin Purse of Charity",
	"Scriptures",
	"Promissory Note",
	"Antique Panoply",
	"Matured Greenwarish",
	"Pretty Stone",
	"Champion's Writ",
	"Warden's Writ",
	"Archmage's Writ",
	"Quina's Note",
	"Pilgrim's Charm",
	"Unbowed Tree",
	"Eager Fang",
	"Gran Soren Uniform",
	"Strongwarish",
	"Badge of Merit",
	"Rift Crystal",
	"Unknown Item",
	"Salvation's Badge",
	"Manse Key",
	"Skeleton Key",
	"Love-In-The-Rough",
	"Ne'er-Do-Part",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Wyrmking's Ring",
	"Kept Scrag of Beast",
	"Kept Beast-Steak",
	"Kept Ambrosial Meat",
	"Kept Sour Scrag of Beast",
	"Kept Sour Beast-Steak",
	"Kept Sour Ambrosial Meat",
	"Kept Rotten Scrag of Beast",
	"Kept Rotten Beast-Steak",
	"Kept Rotten Ambrosial Meat",
	"Kept Small Fish",
	"Kept Large Fish",
	"Kept Giant Fish",
	"Kept Small Rank Fish",
	"Kept Large Rank Fish",
	"Kept Giant Rank Fish",
	"Kept Small Rotten Fish",
	"Kept Large Rotten Fish",
	"Kept Giant Rotten Fish",
	"Kept Berry",
	"Kept Apple",
	"Kept Grandgrapes",
	"Kept Moldy Berry",
	"Kept Moldy Apple",
	"Kept Moldy Grandgrapes",
	"Kept Rotten Berry",
	"Kept Rotten Apple",
	"Kept Rotten Grandgrapes",
	"Kept Twigbean",
	"Kept Carrot",
	"Kept Pumpkin",
	"Kept Moldy Twigbean",
	"Kept Moldy Carrot",
	"Kept Moldy Pumpkin",
	"Kept Rotten Twigbean",
	"Kept Rotten Carrot",
	"Kept Rotten Pumpkin",
	"Kept Egg",
	"Kept Golden Egg",
	"Kept Rotten Egg",
	"Kept Sunbright",
	"Kept Moonglow",
	"Kept Wilted Blossom",
	"Ferrystone",
	"Maker's Finger",
	"Portcrystal",
	"Wakestone",
	"Wakestone Shard",
	"Wyrmward Perfume",
	"Salomet's Grimoire Forgery",
	"Gold Idol Forgery",
	"Silver Idol Forgery",
	"Bronze Idol Forgery",
	"Wyrmking's Ring Forgery",
	"Rift Fragment",
	"Rift Cluster",
	"Dragon's Gaze",
	"Confidential Letter Forgery",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Iron Sword",
	"Cutlass",
	"Silver Rapier",
	"Golden Rapier",
	"Aneled Rapier",
	"Broadsword",
	"Trusty Sword",
	"Undulant Sword",
	"Undulant Gold",
	"Undulant Black",
	"Crossed Cinquedea",
	"Dragon's Dogma",
	"Bastard Sword",
	"Golden Bastard",
	"Aneled Bastard",
	"Carnation",
	"Tight Cinquedea",
	"Ascalon",
	"Wounded Fury",
	"Force Hatchet",
	"Rusted Sword",
	"Mace",
	"Thousand Troops",
	"Obliteratrix",
	"Golden Obliteratrix",
	"Aneled Obliteratrix",
	"Steel Beak",
	"Beak of Gold",
	"Aneled Beak",
	"Threaded Cudgel",
	"Dragon's Toll",
	"Morgenstern",
	"Bloodthirsty Beak",
	"Thousand Stings",
	"Golden Stings",
	"Aneled Stings",
	"Ingot Club",
	"Totem Mace",
	"Dragon's Presence",
	"Sickening Skull",
	"Royal Alms",
	"Rusted Mace",
	"Two-Hander",
	"Steel Greatsword",
	"Lifetaker",
	"Soultaker",
	"Soulbreaker",
	"War Blade",
	"Flamberge",
	"Cassardi Flamberge",
	"Saving Grace",
	"Dwells-In-Light",
	"Dragon's Bite",
	"Lancer's Sword",
	"Golden Lance",
	"Aneled Lance",
	"Gryphic Victory",
	"Gryphic Gold",
	"Gryphic Black",
	"Wounded Heart",
	"Dragon's Flight",
	"Iraklis",
	"Rusted Greatsword",
	"Judgment",
	"Mounted Pale",
	"Golden Pale",
	"Aneled Pale",
	"Cyclops Sigil",
	"Golden Cyclops Sigil",
	"Aneled Cyclops Sigil",
	"Triple Tooth",
	"Teeth of Gold",
	"Aneled Tooth",
	"Ferric Talon",
	"Bloody Thistle",
	"Steel Urchin",
	"Angel's Fist",
	"Dragon's Repast",
	"Black Matter",
	"Chestcaver",
	"Unknown Item",
	"Cyclop's Bane",
	"Stamina Hammer",
	"Rusted Warhammer",
	"Throatcutters",
	"Signs of Valor",
	"Crimson Teeth",
	"Bardiche Daggers",
	"Golden Bardiches",
	"Aneled Bardiches",
	"Vouge Daggers",
	"Divine Razors",
	"Stilettos",
	"Golden Stilettos",
	"Aneled Stilettos",
	"Criteria",
	"Dragon's Vein",
	"Dragon's Pain",
	"Snagdaggers",
	"Snags of Gold",
	"Aneled Snags",
	"Unknown Item",
	"Saurian Bane",
	"Dowsing Spikes",
	"Rusted Daggers",
	"Wooden Staff",
	"Favored Flower",
	"Volant White",
	"Unfettered Claw",
	"Golden Claw",
	"Aneled Claw",
	"Cast Stone",
	"Dragon's Nous",
	"Ironclad Staff",
	"Unspoken Grace",
	"Golden Grace",
	"Aneled Grace",
	"Anchor To Heaven",
	"Path To Heaven",
	"Gleam Of Heaven",
	"Favored Canopy",
	"Frigid Finger",
	"Unknown Item",
	"Goblin Bane",
	"Legion's Might",
	"Rusted Staff",
	"Common Archistaff",
	"Favored Branches",
	"Talarian White",
	"Plucked Heart",
	"Solar Providence",
	"Eclipsed Providence",
	"Dragon's Wit",
	"Keen Dragon's Wit",
	"Grievous Horns",
	"Grievous Gold",
	"Grevious Black",
	"Meniscus",
	"Golden Meniscus",
	"Aneled Meniscus",
	"Helical Archistaff",
	"Solar Numen",
	"Dragons Risen",
	"Unknown Item",
	"Evil Eyesight",
	"Caged Fury",
	"Rusted Archistaff",
	"Eden's Warden",
	"Caladbolg",
	"Almace",
	"Crescending Roar",
	"Font of Fire",
	"Malignance",
	"Ardent Will",
	"Fiery Talon",
	"Rooted Gloom",
	"Crimson Glare",
	"Thunderclap",
	"Divine Axis",
	"Algid Bloom",
	"Iron Shield",
	"Pelta",
	"Round Shield",
	"Gran Soren Shield",
	"Mark of the Chimera",
	"Orilux Shield",
	"Lustrous Targe",
	"Sable Sentinel",
	"Dragon's Aegis",
	"Feather-Light Pelta",
	"Scarred Sentinel",
	"Dragon's Den",
	"Hellfang",
	"Brutish Wall",
	"Rusted Shield",
	"Wooden Wall",
	"Magick Buckler",
	"Fine Magick Buckler",
	"Lustrous Greatshield",
	"Blue Kite Shield",
	"Wizard's Vizard",
	"Knight's Honor",
	"Angel's Sanctum",
	"Dark Buckler",
	"Dragon's Faith",
	"Unknown Item",
	"Unknown Item",
	"Zombiebane",
	"Brilliance",
	"Rusted Magick Shield",
	"Shortbow",
	"Direwolf Bow",
	"Sylvan Bow",
	"Fluted Bow",
	"Dragon's Rancor",
	"Hunter's Bow",
	"Pleached Limbs",
	"Fey Whisper",
	"Stalwart Bow",
	"Unknown Item",
	"Unknown Item",
	"Griffinbane",
	"Repeller Bow",
	"Rusted Bow",
	"Plain Longbow",
	"Reinforced Longbow",
	"Bespoke Longbow",
	"Noble Limbs",
	"Veteran's Arc",
	"Dragon's Blink",
	"Savage Fang",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Hydra Husk",
	"Bezel Crown",
	"Rusted Longbow",
	"Gimble Gyre",
	"Terminal Gyre",
	"Herald's Helix",
	"Master's Merle",
	"Dragon's Breath",
	"Dragon's Quickening",
	"Magian Crutch",
	"Metered Catharsis",
	"Militant Dove",
	"Rusted Spellbow",
	"Cursed Bite",
	"Cursed Light",
	"Devilsbane",
	"Shooting Star",
	"Magebreaker",
	"Virge of Madness",
	"Unknown Item",
	"Unknown Item",
	"Scorched Pelta",
	"Lambent Shield",
	"Thunder Kite Shield",
	"Scalding Razors",
	"Kunai",
	"Galvanic Razors",
	"Chilling Razors",
	"Heaven's Key",
	"Frozen Tomorrow",
	"Stagnant Surge",
	"Thousandlimbs",
	"White Hawk's Talon",
	"Unknown Item",
	"Plebian Shirt",
	"Cloth Greaves",
	"Faded Vest",
	"Traveler's Shirt",
	"Tunic",
	"Bandages",
	"Cassardi Shift",
	"Fine Cassardi Shirt",
	"Hemp Shirt",
	"Leather Chestguard",
	"Unknown Item",
	"Linen Shirt",
	"Riveted Coat",
	"Assembled Vest",
	"Quilted Jerkin",
	"Cotton Tunic",
	"Lady's Corset",
	"Chain Mail",
	"Braided Shirt",
	"Chainmail Bracers",
	"Bliaut",
	"Light Outfit",
	"Iron Vest",
	"Blessed Vest",
	"Brigandine Jerkin",
	"Hard Leather Plate",
	"Trooper Outfit",
	"Unknown Item",
	"Maiden's Camisole",
	"Unknown Item",
	"Silver Vest",
	"Silver Chestplate",
	"Forest Tunic",
	"Alchemick Vest",
	"Plated Coat",
	"Hunter's Shirt",
	"Gambeson",
	"Doublet",
	"Noblewoman's Corset",
	"Dragonleather Vest",
	"Unknown Item",
	"Abyssinal Outfit",
	"Crimson Jerkin",
	"Silver Cuirass",
	"Marshal's Bracers",
	"Swordsman's Shirt",
	"White Hawk Tunic",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Illusory Broadsword",
	"Illusory Mark of the Chimera",
	"Illusory Brigandine Jerkin",
	"Illusory Laborer's Breeches",
	"Illusory Divine Surcoat",
	"Illusory Shadow Gauntlets",
	"Illusory Shadow Greaves",
	"Illusory Tattered Mantle",
	"Illusory Crossed Cinquedea",
	"Illusory Scarred Sentinel",
	"Illusory Plated Coat",
	"Illusory Laborer's Breeches",
	"Illusory Clerical Cap",
	"Illusory Grand Surcoat",
	"Illusory Steel Gauntlets",
	"Illusory Steel Sabatons",
	"Illusory Vouge Daggers",
	"Illusory Shortbow",
	"Illusory Quiver",
	"Illusory Chainmail Bracers",
	"Illusory Translucent Hosen",
	"Illusory Chestguard",
	"Illusory Bandit's Glove",
	"Illusory Chainmail Skirt",
	"Illusory Ironclad Staff",
	"Illusory Forest Tunic",
	"Illusory Fine Cassardi Hosen",
	"Illusory Wizard's Helm",
	"Illusory Missionary's Robe",
	"Illusory Runic Bangles",
	"Illusory Leather Shoes",
	"Short Pants",
	"Traveler's Tights",
	"Cotton Hosen",
	"Leather Bandings",
	"Cassardi Trousers",
	"Fine Cassardi Hosen",
	"Unknown Item",
	"Hemp Hosen",
	"Worker's Pants",
	"Yellow Gaiters",
	"Half Chain Hosen",
	"Laced Leggings",
	"Brown Leathers",
	"Evening Tights",
	"Bandit Stalkers",
	"Urban Hosen",
	"Twisted Leathers",
	"Seeker Tights",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Laborer's Breeches",
	"White Stockings",
	"Full Chain Hosen",
	"Black Gaiters",
	"Huntsman's Trousers",
	"Braided Hosen",
	"Brown Laced Leggings",
	"Iron Bandings",
	"Silver Hosen",
	"Alchemickal Hosen",
	"Denim Hosen",
	"Silk Lingerie",
	"Swordsman's Pants",
	"White Hawk Leggings",
	"Gransys Flamberge",
	"Boltbringer",
	"Bitter End",
	"Twinpaler",
	"Twinterfang",
	"Devil's Nail",
	"Helmbarte Daggers",
	"Sapfire Daggers",
	"Framae Blades",
	"Chilling Focus",
	"Melting Focus",
	"Dominion Claw",
	"Unknown Item",
	"Unknown Item",
	"Leather Cap",
	"Circlet",
	"Leather Hood",
	"Chain Coif",
	"Faerie Hood",
	"Bronze Sallet",
	"Feather Hood",
	"Verdant Hood",
	"White Cap",
	"Skulker's Mask",
	"Horned Helm",
	"Cyclops Veil",
	"Red Leather Cap",
	"Red Leather Hood",
	"Dragon Band",
	"Wizard's Helm",
	"Lupine Veil",
	"Incognito Mask",
	"Bandit's Mask",
	"Barreled Helm",
	"Leather Circlet",
	"Iron Helm",
	"Gryphic Helm",
	"Assassin's Mask",
	"Iron Headgear",
	"Twilight Hood",
	"Guardian's Hood",
	"Gossip's Mask",
	"Summery Cowl",
	"Chimeric Armet",
	"Lion-Lord's Helm",
	"Crowned Hood",
	"Clerical Cap",
	"Meloirean Helm",
	"Steel Sallet",
	"Coupled Headgear",
	"Archwizard's Helm",
	"Autumn Hood",
	"Laurel Circlet",
	"Meloirean Cyclops Veil",
	"Direwolf Veil",
	"Sultry Cowl",
	"Crimson Armet",
	"Grisly Skull",
	"Golden Lion Helm",
	"Dragon Knight's Helm",
	"Sage's Hood",
	"Barbarian Chief's Helm",
	"Twilight Mask",
	"Diadem",
	"Dragonroar",
	"Hero's Hood",
	"Chaos Helm",
	"Emissary Hood",
	"Monomi Mask",
	"Ancient Circlet",
	"Heresy Hood",
	"Beowulf Mask",
	"Apollo Mask",
	"Siegfried Mask",
	"Saint George Mask",
	"Silver Eyeglasses",
	"Gold Eyeglasses",
	"Black Eyeglasses",
	"Red Eyeglasses",
	"Farewell Hood",
	"Wyrmfyre Vizard",
	"Dragonseye Band",
	"Dragonspulse Circlet",
	"White Hawk Sallet",
	"Bane Archistaff",
	"Hallowed Dragon",
	"Sanguine Stalk",
	"Dragon's Roost",
	"Dread Aspis",
	"Purged Buckler",
	"Diabolic Shield",
	"Dragon's Ire",
	"Darkening Storm",
	"Dragon's Glaze",
	"Revenant Wail",
	"Dragon's Tempest",
	"Blackwing Bow",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Skull Belts",
	"Leather Jacket",
	"Shabby Robe",
	"Bone Armor",
	"Bone Plate Armor",
	"Leather Belts",
	"Sectional Armor",
	"Chestguard",
	"Scholar's Coat",
	"Healer's Robe",
	"Bronze Cuirass",
	"Leather Waistwrap",
	"Mummer's Wear",
	"Bronze Lorica",
	"Hide Armor",
	"Surcoat",
	"Hunter's Jacket",
	"Red Leather Armor",
	"Unknown Item",
	"Missionary's Robe",
	"Frame Plate",
	"Padded Armor",
	"Sectional Iron Plate",
	"Gryphic Armor",
	"Iron Lorica",
	"Weak Guard",
	"Magician's Surcoat",
	"Dalmatica",
	"Grand Surcoat",
	"Summery Pareo",
	"Recluse's Robe",
	"Maiden's Petticoat",
	"Flutter Padding",
	"Chimeric Half Plate",
	"Scale Coat",
	"Rex Lion Padding",
	"Sage's Robe",
	"Animistic Robe",
	"Meloirean Plate",
	"Steel Cuirass",
	"Lamellar Jacket",
	"Cardinal Surcoat",
	"Royal Surcoat",
	"Divine Surcoat",
	"Golden Belt",
	"Sultry Pareo",
	"Crimson Robe",
	"Archer's Culottes",
	"Crimson Plate",
	"Grisly Bone Armor",
	"Golden Lion Padding",
	"Matte Robe",
	"Philosopher's Robe",
	"Red Dragon Scale",
	"Dark Lorica",
	"Berserkin",
	"Hero's Surcoat",
	"Chaos Armor",
	"Emissary Armor",
	"Monomi Coat",
	"Ancient Robe",
	"Heresy Armor",
	"Abyssinal Coat",
	"Solar Armor",
	"Asura Armor",
	"Leather Protector",
	"Swordsman's Plate",
	"White Hawk Half-Plate",
	"Patterned Gambeson",
	"Unknown Item",
	"Delta Guard",
	"Silk Tights",
	"Traveler's Hood",
	"Minstrel's Band",
	"Mistletoe Circlet",
	"Immortal's Helm",
	"Persecutor's Mask",
	"Farseer's Cap",
	"Adept's Hat",
	"Ruminator's Monocle",
	"Nether Helm",
	"Hellfire Helm",
	"Hood of Shadow",
	"Hood of Oblivion",
	"Grave Veil",
	"Carrion Veil",
	"Traveler's Vest",
	"Novice's Coat",
	"Unknown Item",
	"Immortal's Coat",
	"Cursed King's Belt",
	"Trophy Jacket",
	"Adept's Robe",
	"Celestial Armor",
	"Votary's Robe",
	"Traitor's Armor",
	"Hellfire Armor",
	"Coat of Shadow",
	"Coat of Oblivion",
	"Grave Mantle",
	"Carrion Mantle",
	"Wizarding Gloves",
	"Force Bangles",
	"Immortal's Bracers",
	"Trophy Bracers",
	"Dragonwing Gloves",
	"Blessed Sleeves",
	"Wooden Bands",
	"Talismanic Beads",
	"Novice's Bracers",
	"Funnybone Guards",
	"Bandit's Glove",
	"Scholar's Bangle",
	"Navy Leather Gloves",
	"Bronze Gauntlets",
	"Hand Covers",
	"Bronze Bangles",
	"Scale Armguard",
	"Assailant's Bracers",
	"Iron Bracers",
	"Red Leather Glove",
	"Tiger Bangle",
	"Silver Bands",
	"Iron Armguard",
	"Gryphic Gauntlets",
	"Iron Manicae",
	"Assembled Sleeves",
	"Unknown Item",
	"Runic Bangles",
	"Leather Gloves",
	"Master's Bracers",
	"Chimeric Gauntlets",
	"Arm Crest",
	"Scarlet Hand Covers",
	"Jade Bangles",
	"Meloirean Armguard",
	"Steel Gauntlets",
	"Dragon Hide Bracers",
	"Assassin's Armguards",
	"Alchemickal Bangles",
	"Champion's Bangles",
	"Black Leather Gloves",
	"Darkened Gloves",
	"Crimson Gauntlets",
	"Grisly Bracers",
	"Twilight Manicae",
	"Burnished Bracers",
	"Gleaming Bangles",
	"Golden Wristbands",
	"Dragonscale Arm",
	"Shadow Gauntlets",
	"Hero's Gauntlets",
	"Chaos Gauntlets",
	"Emissary Bracers",
	"Monomi Bracers",
	"Ancient Bangles",
	"Heresy Armguards",
	"Abyssinal Bracers",
	"Farewell Gloves",
	"Gloves of Might",
	"Swordsman's Bracers",
	"White Hawk Gauntlets",
	"Crested Armguards",
	"Bonds of the Dragon",
	"Sinner's Gauntlets",
	"Hellfire Gauntlets",
	"Grave Claws",
	"Carrion Claws",
	"Worker's Gloves",
	"Unknown Item",
	"Budget Greaves",
	"Leather Cuisses",
	"Leather Shoes",
	"Novice Breeches",
	"Cassardi Greaves",
	"Metal Greaves",
	"Fur Greaves",
	"Scholar's Boots",
	"Iron Leg Guards",
	"Steel-Toed Boots",
	"Bronze Sabatons",
	"Fur & Cuisses",
	"Riveted Boots",
	"Blue Longkilt",
	"Dusk Shoes",
	"Steel Sabatons",
	"Battle Greaves",
	"Downcuffs & Cuisses",
	"Red Leather Cuisses",
	"Mage's Shoes",
	"Over-Knee Boots",
	"Scale Greaves",
	"Iron Boots",
	"Iron Cuisses",
	"Gryphic Greaves",
	"Chainmail Skirt",
	"Assembled Breeches",
	"Wizard's Boots",
	"Red Longkilt",
	"Fine Over-Knee Boots",
	"Raptor Cuisses",
	"Gloaming Shoes",
	"Chimeric Sabatons",
	"Thick Fur Greaves",
	"Assassin's Breeches",
	"Nimble Cuisses",
	"Red Over-Knee Boots",
	"Meloirean Greaves",
	"Leather Ocreae",
	"Striker's Greaves",
	"Royal Cuisses",
	"Purple Longkilt",
	"Molten Boots",
	"Dark Over-Knee Boots",
	"Flame Skirt",
	"Superior Cuisses",
	"Crimson Sabatons",
	"Grisly Greaves",
	"Carmine Breeches",
	"Exotic High Boots",
	"Shadow Greaves",
	"Dragonbeards",
	"Twilight Greaves",
	"Holy Cuisses",
	"Hero's Cuisses",
	"Chaos Greaves",
	"Emissary Greaves",
	"Monomi Greaves",
	"Ancient Greaves",
	"Heresy Greaves",
	"Abyssinal Greaves",
	"Swordsman's Greaves",
	"White Hawk Cuisses",
	"Foreign Waistguard",
	"Hinterland Waistguard",
	"Extrinsic Waistguard",
	"Immortal's Sabatons",
	"Trophy Boots",
	"Mercenary Slogs",
	"Dragonwing Boots",
	"Assault Boots",
	"Apostate's Anklet",
	"Betrayer's Greaves",
	"Hellfire Greaves",
	"Grave Greaves",
	"Carrion Greaves",
	"Tormenter's Mask",
	"Dragonwing Circlet",
	"Gauntlets of Shadow",
	"Gauntlets of Oblivion",
	"Boots of Shadow",
	"Boots of Oblivion",
	"Adept's Mantle",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Leather Cape",
	"Shed Cape",
	"Shoulder Cape",
	"Ebon Neck Wrap",
	"Scholar's Cape",
	"Mahogany Cape",
	"Direwolf Cape",
	"Adventurer's Cloak",
	"Feather Cape",
	"Knight's Mantle",
	"Harpy Cloak",
	"Alchemickal Cloak",
	"Violet Neck Wrap",
	"Paladin's Mantle",
	"Gryphic Cloak",
	"Scarlet Cape",
	"Pauldron",
	"Feral Cape",
	"Royal Mantle",
	"Dignified Cape",
	"Dragon Knight's Cloak",
	"Ancient Cape",
	"Lordly Cloak",
	"Hero's Cape",
	"Monomi Neck Wrap",
	"Heresy Cloak",
	"Nebula Cape",
	"Magnanimous Cloak",
	"Farewell Cloak",
	"Baleful Nails",
	"Ogre Bone",
	"Reinforced Nails",
	"Barbed Nails",
	"Ring of Gules",
	"Ring of Azure",
	"Ring of Purpure",
	"Ring of Sable",
	"Ring of Argent",
	"Ring of Ruby",
	"Ring of Sapphire",
	"Ring of Amethyst",
	"Ring of Pearl",
	"Ring of Onyx",
	"Rose Ring",
	"Iris Ring",
	"Violet Ring",
	"Lily Ring",
	"Aeonium Ring",
	"Cleansing Earring",
	"Restless Earring",
	"Nimble Earring",
	"Free-Spoken Earring",
	"Benevolent Earring",
	"Sight Earring",
	"Faithful Earring",
	"Exuberant Earring",
	"Stalwart Earring",
	"Noble Earring",
	"Harmonious Earring",
	"Dignified Earring",
	"Indomitable Earring",
	"Dragonblood",
	"Silver Ring",
	"Golden Ring",
	"Platinum Ring",
	"Red Star Ring",
	"Red Star Earring",
	"Green Star Ring",
	"Green Star Earring",
	"Blue Star Ring",
	"Blue Star Earring",
	"Premium Ring",
	"Premium Earring",
	"Wyrm Hunt Mantle",
	"Beastly Mantle",
	"Conqueror's Mantle",
	"Tattered Mantle",
	"Swordsman's Mantle",
	"White Hawk Cape",
	"Divine Embrace",
	"Unknown Item",
	"Nomad's Cloak",
	"Sovereign's Mantle",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Blasphemer's Cloak",
	"Hellfire Cloak",
	"Vandal's Ring",
	"Bloody Knuckle",
	"Stonewall Earring",
	"Ring of Desiccation",
	"Ring of Perseverance",
	"Wanderlust Ring",
	"Virtuoso Ring",
	"Preceptor Ring",
	"Master Ring",
	"Savior Ring",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Robe of Enlightenment",
	"Tiara of Enlightenment",
	"Jester's Cap",
	"Wavering Cloth",
	"The Lion's Spine",
	"Vagabond Armor",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Set of Servant's Garb",
	"Set of Duke's Clothing",
	"Set of Salvation Robes",
	"Set of Fisherman's Garb",
	"Set of Fisherman's Tatters",
	"Set of Royal Guard Armor",
	"Set of Lady's Garb",
	"Set of Caretaker's Garb",
	"Forest Tunic Set",
	"Unknown Item",
	"Set of Prisoner's Rags",
	"Set of Jester's Motley",
	"Nameless Armor Set",
	"Captain's Armor Set",
	"Set of Fop's Trek Wear",
	"Set of Voldoan Armor",
	"Set of Priest Vestments",
	"Set of Lady's Trek Wear",
	"Set of Queen's Clothing",
	"Set of Nun Vestments",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Royal Banner",
	"Enlistment Corps Banner",
	"War Bugle",
	"Fishing Bob",
	"Bucket",
	"Hoe",
	"Spade",
	"Scythe",
	"Hammer",
	"Trowel",
	"Work Table",
	"Quill",
	"Wooden Board",
	"Tray",
	"Sconce",
	"Blank Scroll",
	"Broom",
	"Ancient Scroll",
	"Shackle",
	"Large Coin Pouch",
	"Coin Pouch",
	"Small Coin Pouch",
	"Giant Coin Pouch",
	"Hunk of Ore",
	"Goblin Horn",
	"Wormwood Sap",
	"Iron Blade Piece",
	"Slate-Colored Horn",
	"Curious Wine",
	"Ebon Blade Piece",
	"Night Terror's Horn",
	"Blood Decanter",
	"Small Fang",
	"Wolf Pelt",
	"Large Fang",
	"Direwolf Pelt",
	"Hellhound Fang",
	"Hellhound Pelt",
	"Ember Crystal",
	"Saurian Scale",
	"Poison Sac",
	"Fisheye Stone",
	"Saurian Tail",
	"Striped Saurian Skin",
	"Yellow Poison Sac",
	"Incarnadine Scale",
	"Inky Saurian Skin",
	"Acid Sac",
	"Snowy Saurian Skin",
	"Argentine Sac",
	"Purpure Crystal",
	"Harpy Pinion",
	"Harpy Rectrix",
	"Elongated Claw",
	"Glacial Pinion",
	"Glacial Rectrix",
	"Spurious Wing",
	"Sinistone",
	"Petrifactor",
	"Bastard Wing",
	"Shroud",
	"Putrid Gold Tooth",
	"Necrophagous Loin",
	"Rusted Plate",
	"Aged Insignia",
	"Hex Runes",
	"Brawn Runes",
	"Miasmite Shard",
	"Miasmite",
	"Eldricite Shard",
	"Eldricite",
	"Astracite Shard",
	"Astracite",
	"Black Crystal",
	"Immortelle",
	"Vengeful Mirror",
	"Wailing Crystal",
	"Craft Bone",
	"Scrap Iron",
	"Hard Bone",
	"Dark Peridot",
	"Fell-Lord's Bone",
	"Lordly Emblem",
	"Mandrake",
	"Torn Grimoire Preface",
	"Torn Grimoire Appendix",
	"Agate",
	"Forgotten Arcanum",
	"Pigeon's Blood",
	"Rugged Bone",
	"Rugged Tusk",
	"Misshapen Eye",
	"Ogre Spur",
	"Ogre Tooth",
	"Unspeakable Meat",
	"Dappled Ore",
	"Magick Medal",
	"Hunk of Gold Ore",
	"Electrum",
	"Griffin Pinion",
	"Great Griffin Claw",
	"Slick Black Pinion",
	"Cockatrice Beak",
	"Hydra's Lifeblood",
	"Poison Hydra Fang",
	"Black Hydra Scale",
	"White Hydra Scale",
	"Hydra Gallstone",
	"Freakish Claw",
	"Freakish Mane",
	"Freakish Scale",
	"Black Freakish Claw",
	"Black Freakish Mane",
	"Black Freakish Horn",
	"Black Freakish Scale",
	"Malecryst",
	"Evil Eyeball",
	"Malecryst Shard",
	"Dragon Scale",
	"Crimson Dragon Scale",
	"Putrid Dragon Scale",
	"Great Dragon Horn",
	"Great Dragon Alula",
	"Great Dragon Claw",
	"Great Dragon Fang",
	"Indurated Dragonsblood",
	"Dragon Horn",
	"Dragon Claw",
	"Azure Dragon Scale",
	"Amber Dragon Scale",
	"Virid Dragon Scale",
	"Rabbit Pelt",
	"Snakeskin",
	"Spider Venom",
	"Unknown Item",
	"Desiccated Herbs",
	"Stone-Moss Poultice",
	"Foreign Medicament",
	"Pickled Mushrooms",
	"Backfat Oil",
	"Staminal Drench",
	"Crimson Concoction",
	"Cerulean Concoction",
	"Verdigris Concoction",
	"Violet Concoction",
	"Balmy Perfume",
	"Balmy Incense",
	"Rousing Perfume",
	"Rousing Incense",
	"Herb Ale",
	"Select Herb Ale",
	"Distilled Herb Ale",
	"Secret Herb Ale",
	"Finest Herb Ale",
	"Fragrant Herb Ale",
	"Perfect Herb Ale",
	"Detoxicating Powder",
	"Oak Leaf Oil",
	"Vigilite",
	"Throat Remedy",
	"Peppermint Seed",
	"Nostalgia Dust",
	"Drop of Deliverance",
	"Frozen Holy Water",
	"Cockatrice Liquor",
	"Font of Vigor",
	"Font of Constitution",
	"Tagilus's Miracle",
	"Steel Nut Salve",
	"Salomet's Secret",
	"Decoction of Bandlily",
	"Mushroom Potage",
	"Sobering Wine",
	"Martyr's Talisman",
	"Golden Talisman",
	"Mage's Talisman",
	"Iridescent Talisman",
	"Vigor Extract",
	"Serenity Extract",
	"Silverwheat Paste",
	"Goldbean Grind",
	"Leaden Globe",
	"Headless Icon",
	"Warlock's Incense",
	"Cleric's Incense",
	"Goddess Cameo",
	"Wroth Mask",
	"Decaying Grimoire",
	"\"The Sundering Spear\" Tome",
	"Fulgurous Lord Tome",
	"\"Winter's Path\" Tome",
	"Jewel of Silence",
	"Jewel of Darkness",
	"Jewel of Time",
	"Jewel of Health",
	"Jewel of Endurance",
	"Jewel of Petrifaction",
	"Jewel of Toxicity",
	"Jewel of Sleep",
	"Jewel of Vicissitude",
	"Unknown Item",
	"Sweet Pollen",
	"Cloudwine",
	"Shadowcap",
	"Unremarkable Ore",
	"White Sage",
	"Sand-Layer Ore",
	"Stagnant Shroom",
	"Purple Anise",
	"Firefly Stone",
	"Capeflower",
	"King Bay Leaf",
	"Cassardite",
	"Lava Flower",
	"Catacomb Gold",
	"Flammica",
	"Unknown Item",
	"Imperial Acid",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Copperstone",
	"Godsthrone Blossom",
	"Lodestone",
	"Reminishroom",
	"Destiny Grass",
	"Devilwort",
	"Fiend's Perch",
	"Grandblossom",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Gloamcap",
	"Cragwort",
	"Burst-Rock",
	"Windmill Flower",
	"Scarlet Angelica",
	"Nightcry",
	"Waterfell Gentian Root",
	"Waterfell Gentian Leaf",
	"z",
	"Polar Mushroom",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Alluvial Yore-Ore",
	"Bladeleaf",
	"Shiverberry",
	"Southron Iron",
	"Southron Oregano",
	"Thornflower",
	"Chaffstem",
	"Nurse Log Sap",
	"Unknown Item",
	"Gransys Herb",
	"Toadstool Sitter",
	"Spiny Nut",
	"Loneflower",
	"Anathema Grass",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Wintry Herb",
	"White Orchid",
	"Sorrowstone",
	"Jasper Blossom",
	"Unknown Item",
	"Unknown Item",
	"Ancient Ore",
	"Droughtshroom",
	"Cursed Carving",
	"Snakeskin Purse",
	"Priceless Artifact",
	"Brick",
	"Festival Pie",
	"Gran Soren Rubble",
	"Noonflower",
	"Unknown Item",
	"Tuft of Hair",
	"Spring Water",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Symone's Petition",
	"Fedel's Petition",
	"Geffrey's Petition",
	"Jasper's Condemnation",
	"Sara's Condemnation",
	"Pip's Condemnation",
	"Soiled Affidavit",
	"Tattered Affidavit",
	"Sweat-Stained Affidavit",
	"Blurred Affidavit",
	"Chamberlain's Affidavit",
	"Dirty Affidavit",
	"Moldy Affidavit",
	"Worn Affidavit",
	"Ripped Affidavit",
	"Gift Ledger",
	"Drake's Tear",
	"Wyrm's Tear",
	"Wyvern's Tear",
	"Scather's Elixir",
	"Medicant's Elixir",
	"Mitigator's Elixir",
	"Challenger's Elixir",
	"Utilitarian's Elixir",
	"Guardian's Elixir",
	"Nexus's Elixir",
	"Pioneer's Elixir",
	"Acquisitor's Elixir",
	"Neutralizing Elixir",
	"Hobgoblin Tactics",
	"Goblin Strategies",
	"Wolf Strategy Vol. 1",
	"Wolf Strategy Vol. 2",
	"Wolf Strategy Vol. 3",
	"Skeleton Knight Tactics",
	"Skeleton Strategies",
	"Saurian Tactics Vol. 1",
	"Saurian Tactics Vol. 2",
	"Saurian Strategy Vol. 1",
	"Saurian Strategy Vol. 2",
	"Saurian Strategy Vol. 2",
	"Undead Tactics Vol. 1",
	"Undead Tactics Vol. 2",
	"Undead Strategy Vol. 1",
	"Undead Strategy Vol. 2",
	"Harpy Strategies",
	"Ghost Tactics Vol. 1",
	"Ghost Tactics Vol. 2",
	"Ghost Strategies",
	"Ogre Strategy Vol. 1",
	"Ogre Strategy Vol. 2",
	"Cyclops Tactics",
	"Cyclops Strategy Vol. 1",
	"Cyclops Strategy Vol. 2",
	"Golem Tactics",
	"Golem Strategy Vol. 1",
	"Golem Strategy Vol. 2",
	"Chimera Tactics",
	"Chimera Strategy Vol. 1",
	"Chimera Strategy Vol. 2",
	"Hydra Tactics",
	"Hydra Strategy Vol. 1",
	"Hydra Strategy Vol. 2",
	"Griffin Strategy Vol. 1",
	"Griffin Strategy Vol. 2",
	"Griffin Strategy Vol. 3",
	"Cockatrice Strategy Vol. 1",
	"Cockatrice Strategy Vol. 2",
	"Evil Eye Strategy Vol. 1",
	"Evil Eye Strategy Vol. 2",
	"Vile Eye Strategy Vol. 1",
	"Vile Eye Strategy Vol. 2",
	"Wight Tactics",
	"Lich Tactics",
	"Draconian Strategy Vol. 1",
	"Draconian Strategy Vol. 2",
	"<ITNO 185> 34",
	"<ITNO 185> 51",
	"<ITNO 185> 77",
	"<ITNO 185> 33",
	"<ITNO 185> 69",
	"<ITNO 185> 81",
	"<ITNO 185> 82",
	"<ITNO 185> 83",
	"<ITNO 185> 84",
	"<ITNO 185> 85",
	"<ITNO 185> 86",
	"<ITNO 185> 1",
	"<ITNO 185> 2",
	"<ITNO 185> 3",
	"<ITNO 185> 70",
	"<ITNO 185> 4",
	"<ITNO 185> 11",
	"<ITNO 185> 22",
	"<ITNO 185> 31",
	"<ITNO 185> 12",
	"<ITNO 185> 32",
	"<ITNO 185> 5",
	"<ITNO 185> 62",
	"<ITNO 185> 14",
	"<ITNO 185> 92",
	"<ITNO 185> 15",
	"<ITNO 185> 6",
	"<ITNO 185> 9",
	"<ITNO 185> 38",
	"<ITNO 185> 37",
	"<ITNO 185> 63",
	"<ITNO 185> 66",
	"<ITNO 185> 61",
	"<ITNO 185> 67",
	"<ITNO 185> 94",
	"<ITNO 185> 8",
	"Vermillion Face Pigment",
	"Gold Face Pigment",
	"Bright Green Face Pigment",
	"Turquoise Face Pigment",
	"Blue Face Pigment",
	"Lavender Face Pigment",
	"White Face Pigment",
	"Red Hair Dye",
	"Pink Hair Dye",
	"Sky Blue Hair Dye",
	"Cornflower Blue Hair Dye",
	"Pine Green Hair Dye",
	"Bright Green Hair Dye",
	"Yellow Hair Dye",
	"Red Skin Pigment",
	"Yellow Skin Pigment",
	"Green Skin Pigment",
	"Blue Skin Pigment",
	"Plum Skin Pigment",
	"Ash Gray Skin Pigment",
	"Ivory Skin Pigment",
	"Art of Metamorphosis",
	"Secret of Metamorphosis",
	"<ITNO 185> 95",
	"<ITNO 185> 96",
	"<ITNO 185> 68",
	"<ITNO 185> 65",
	"<ITNO 185> 72",
	"<ITNO 185> 93",
	"<ITNO 185> 73",
	"<ITNO 185> 100",
	"<ITNO 185> 98",
	"<ITNO 185> 79",
	"<ITNO 185> 74",
	"<ITNO 185> 27",
	"<ITNO 185> 71",
	"<ITNO 185> 7",
	"<ITNO 185> 21",
	"<ITNO 185> 44",
	"<ITNO 185> 43",
	"<ITNO 185> 47",
	"<ITNO 185> 45",
	"<ITNO 185> 46",
	"<ITNO 185> 42",
	"<ITNO 185> 49",
	"<ITNO 185> 41",
	"<ITNO 185> 48",
	"<ITNO 185> 50",
	"<ITNO 185> 75",
	"<ITNO 185> 23",
	"<ITNO 185> 54",
	"<ITNO 185> 19",
	"<ITNO 185> 88",
	"<ITNO 185> 89",
	"<ITNO 185> 16",
	"<ITNO 185> 52",
	"<ITNO 185> 28",
	"<ITNO 185> 29",
	"<ITNO 185> 80",
	"<ITNO 185> 58",
	"<ITNO 185> 35",
	"<ITNO 185> 40",
	"<ITNO 185> 39",
	"<ITNO 185> 87",
	"<ITNO 185> 56",
	"<ITNO 185> 55",
	"<ITNO 185> 17",
	"<ITNO 185> 30",
	"<ITNO 185> 64",
	"<ITNO 185> 60",
	"<ITNO 185> 97",
	"<ITNO 185> 20",
	"<ITNO 185> 13",
	"<ITNO 185> 36",
	"<ITNO 185> 59",
	"<ITNO 185> 57",
	"<ITNO 185> 24",
	"<ITNO 185> 18",
	"<ITNO 185> 25",
	"<ITNO 185> 26",
	"<ITNO 185> 53",
	"<ITNO 185> 99",
	"<ITNO 185> 90",
	"<ITNO 185> 10",
	"<ITNO 185> 76",
	"<ITNO 185> 78",
	"<ITNO 185> 91",
	"Unknown Item",
	"Bitterblack Novelty Lv.1",
	"Bitterblack Novelty Lv.2",
	"Bitterblack Novelty Lv.3",
	"Bitterblack Gear Lv.1",
	"Bitterblack Gear Lv.2",
	"Bitterblack Gear Lv.3",
	"Bitterblack Weapon Lv.1",
	"Bitterblack Weapon Lv.2",
	"Bitterblack Weapon Lv.3",
	"Bitterblack Armor Lv.1",
	"Bitterblack Armor Lv.2",
	"Bitterblack Armor Lv.3",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Moonbeam Gem",
	"Macabre Sculpture",
	"Void Key",
	"Fiend-luring Incense",
	"Eternal Ferrystone",
	"Invalid Message",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Unknown Item",
	"Lava Rock",
	"Hunk of Platinum",
	"Moonstone",
	"Diamond",
	"Rubicite",
	"Kingwarish",
	"Lunanise",
	"Corpse Nettle",
	"Nightfall Cresset",
	"Cragshadow Morel",
	"Crimplecap",
	"Pyrepipe",
	"Unknown Item",
	"Rift Crystal Speck",
	"Rift Crystal Flake",
	"Rift Crystal Fragment",
	"Rift Crystal Chunk",
	"Rift Bicrystal",
	"Rift Polycrystal",
	"Perfect Rift Crystal",
	"Daimon's Claw",
	"Daimon's Horn",
	"Vile Wakestone",
	"Sorcerer's Quartz",
	"Violet Carapace",
	"Abyssal Eye",
	"Cursed Dragon Scale",
	"Cursed Dragon Horn",
	"Netherstone",
	"Corrupt Remains",
	"Ruinous Relic",
	"Sinister Hide",
	"Sinister Fang",
	"Beastial Eye",
	"Scythe Shard",
	"Bone Lantern",
	"Ox Horn",
	"Bloodied Chain",
	"Blue Iron Buckles",
	"Macabre Eye",
	"Cyclops Fang",
	"Rugged Femur",
	"Fae-Silver Plate",
	"Phantom Orb",
	"Elder Ogre Claw",
	"Elder Ogre Fang",
	"Poxy Flesh",
	"Bright Amber Scale",
	"Firedrake Fang",
	"Bright Azure Scale",
	"Frostwyrm Scute",
	"Bright Virid Scale",
	"Thunderwyvern Horn",
	"Supple Dragon Pelt",
	"Greatwyrm Stone",
	"Warmonger's Horn",
	"Shamanic Reagents",
	"Skull Pendant",
	"Gnarled Fingernails",
	"Befouled Gold Veneer",
	"Tainted Silver Veneer",
	"Bone Crest",
	"Great Bone Shard",
	"Gargantuan Skull",
	"Rotten Baneflesh",
	"Fetid Gallstone",
	"Banshee Locks",
	"Banshee Larynx",
	"Siren Patagium",
	"Siren Tailfin",
	"Strigoi Barb",
	"Bloodred Crystal",
	"Infernal Hide",
	"Crimson Stone",
	"Lizardscale Pelt",
	"Lizard Horn",
	"Venomous Cuspid",
	"Mottled Leather",
	"Septiscopic Crystal",
	"Leapworm Jelly",
	"Maleficent Heart Shard",
	"Maleficent Heart",
	"Sullied Rift Fragment",
	"Bloodstained Periapt",
	"Idol of the All-Mother",
	"Striped Pelt",
	"Ironblack Pelt",
	"Moonshimmer Pelt",
	"Large Fisheye Stone",
	"Unknown Item",
	"Scroll of Predation",
	"Scroll of Fortune",
	"Scroll of Tenacity",
	"Scroll of Conveyance",
	"Scroll of Acquisition",
	"Scroll of Prolongation",
	"Unknown Item",
	"Scroll of Mettle",
	"Scroll of Athleticism",
	"Scroll of Recuperation",
	"Scroll of Adhesion",
	"Scroll of Opportunism",
	"Scroll of Flow",
	"Scroll of Grace",
	"Scroll of Facility",
	"Elite Lantern",
	"Unknown Item",
	"Ring of Thrift",
	"Elite Lantern (Half-Full)",
	"Elite Lantern (No Fuel)",
	"Unknown Item",
	"Expediting Papers",
	"Unknown Item",
	"Unknown Item",
	"Light Pickaxe",
	"Staff-Bearer's Ring (DL)",
	"Liftstone (DL)",
	"Swordsman's Ring (DL)",
	"Daggerist's Ring (DL)",
	"Liftstone (DL)",
	"Rancid Bait Meat",
	"Fiendish Essence",
	"Fiendish Extract",
	"Month-Dried Harspud",
	"Decade-Dried Harspud",
	"Liquid Effluvium",
	"Liftstone (DL)",
	"Dreamwing Nostrum",
	"Jewel of Antilight",
	"Jewel of Summoning",
	"\"Shattered Earth\" Tome",
	"\"Surging Light\" Tome",
	"Lordly Tonic",
	"Godly Analeptic",
	"Auspicious Incense",
	"Vivifying Incense",
	"Liftstone",
	"Swordsman's Ring",
	"Swordsman's Band",
	"Shieldsman's Ring",
	"Daggerist's Ring",
	"Daggerist's Band",
	"Bowman's Ring",
	"Staff-Bearer's Ring",
	"Staff-Bearer's Band",
	"Magick Shieldsman's Ring",
	"Magick Shieldsman's Band",
	"Magick Bowman's Ring",
	"Magick Bowman's Band",
	"Fighter's Ring",
	"Fighter's Band",
	"Strider's Ring",
	"Strider's Band",
	"Mage's Ring",
	"Mage's Band",
	"Warrior's Ring",
	"Warrior's Band",
	"Ranger's Ring",
	"Ranger's Band",
	"Sorcerer's Ring",
	"Sorcerer's Band",
	"Mystic Knight's Ring",
	"Mystic Knight's Band",
	"Magick Archer's Ring",
	"Magick Archer's Band",
	"Assassin's Ring",
	"Assassin's Band",
	"Staff Enchanter's Ring",
	"Staff Enchanter's Band",
	"Shield Enchanter's Ring",
	"Shield Enchanter's Band"
};
